#!/usr/bin/env python3

import sys
from geospy_main import locate_instagram_user, locate_ip, banner
from termcolor import colored

def help_menu():
    print(colored("Usage:", "cyan"))
    print("  geospy username <insta_username>  - Track Instagram geotags")
    print("  geospy ip <ip_address>            - Geolocate an IP address")

def main():
    banner()

    if len(sys.argv) < 3:
        help_menu()
        return

    command = sys.argv[1]
    value = sys.argv[2]

    if command == "username":
        print(colored(f"[+] Scanning Instagram user: {value}", "yellow"))
        locate_instagram_user(value)

    elif command == "ip":
        print(colored(f"[+] Scanning IP address: {value}", "yellow"))
        locate_ip(value)

    else:
        print(colored("[!] Unknown command", "red"))
        help_menu()

if __name__ == "__main__":
    main()
